config/routes.rb
Rails.application.routes.draw do
  root 'stories#index'
  get 'sessions/new'
  get  '/signup',  to: 'users#new'
  resources :users
  get    '/login',   to: 'sessions#new'
  post   '/login',   to: 'sessions#create'
  delete '/logout',  to: 'sessions#destroy'
  resources :stories, only: [:index, :show]
  get '/new_story', to: 'stories#new_root'
  post '/stories', to: 'stories#create'
  post '/votes', to: 'votes#create'
  delete '/votes', to: 'votes#destroy'
  resources :account_activations, only: [:edit]
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Democrastory</title>
    <%= csrf_meta_tags %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
      <!--[if lt IE 9]>
      <script src="//cdnjs.cloudflare.com/ajax/libs/html5shiv/r29/html5.min.js">
      </script>
    <![endif]-->
  </head>

  <body>
    <header class="navbar navbar-fixed-top navbar-inverse">
      <div class="container">
        <nav>
          <ul class="nav navbar-nav">
            <li><%= link_to "Democrastory", root_path, id: "brand" %></li>
          </ul>
          <ul class="nav navbar-nav navbar-right">
            <% if logged_in? %>
              <li>
                <%= link_to "Log out", logout_path, method: "delete" %>
              </li>
            <% else %>
              <li><%= link_to "Log in", login_path %></li>
              <li><%= link_to "Sign up", signup_path %></li>
            <% end %>
          </ul>
        </nav>
      </div>
    </header>
    <div class="container">
      <div class="row">
        <span class="col-xs-3"></span>
        <span class="col-xs-6">
          <% if flash[:info] %>
            <div class="alert alert-info">
              <%= flash[:info] %>
            </div>
          <% elsif flash[:success] %>
            <div class="alert alert-success">
              <%= flash[:success] %>
            </div>
          <% elsif flash[:warning] %>
            <div class="alert alert-warning">
              <%= flash[:warning] %>
            </div>
          <% elsif flash[:danger] %>
            <div class="alert alert-danger">
              <%= flash[:danger] %>
            </div>
          <% end %>
        </span>
        <span class="col-xs-3"></span>
      </div>
      <%= yield %>
    </div>
  </body>
</html>